export const LlmErrorCode = {
  CONNECTION_NOT_FOUND: "LLM_CONNECTION_NOT_FOUND",
  CONNECTION_DISABLED: "LLM_CONNECTION_DISABLED",

  PROVIDER_AUTH_FAILED: "LLM_PROVIDER_AUTH_FAILED",
  PROVIDER_UNREACHABLE: "LLM_PROVIDER_UNREACHABLE",

  MODEL_NOT_FOUND: "LLM_MODEL_NOT_FOUND",
  MODEL_UNAVAILABLE: "LLM_MODEL_UNAVAILABLE",
  MODEL_CAPABILITY_MISMATCH: "LLM_MODEL_CAPABILITY_MISMATCH",

  INPUT_TOKENS_EXCEEDED: "LLM_INPUT_TOKENS_EXCEEDED",
  OUTPUT_TOKENS_EXCEEDED: "LLM_OUTPUT_TOKENS_EXCEEDED",
  INVALID_REQUEST: "LLM_INVALID_REQUEST",
  CONTENT_FILTERED: "LLM_CONTENT_FILTERED",

  RATE_LIMITED: "LLM_RATE_LIMITED",
  QUOTA_EXCEEDED: "LLM_QUOTA_EXCEEDED",
  BILLING_REQUIRED: "LLM_BILLING_REQUIRED",

  CAPABILITY_NOT_SUPPORTED: "LLM_CAPABILITY_NOT_SUPPORTED",
  STREAM_INTERRUPTED: "LLM_STREAM_INTERRUPTED",
  PROVIDER_TIMEOUT: "LLM_PROVIDER_TIMEOUT",
  PROVIDER_ERROR: "LLM_PROVIDER_ERROR",
  UNKNOWN: "LLM_UNKNOWN",
} as const;

export type LlmErrorCode = (typeof LlmErrorCode)[keyof typeof LlmErrorCode];
